FROM nginx:stable-alpine

# 配置时区
ENV TZ=Asia/Shanghai

# 删除默认 nginx 配置
RUN rm -rf /etc/nginx/conf.d/default.conf

# 复制构建产物
COPY dist /usr/share/nginx/html

# 复制 nginx 配置
COPY nginx-antd.conf /etc/nginx/nginx.conf

# 添加 mjs 文件类型支持
RUN echo "types { application/javascript js mjs; }" > /etc/nginx/conf.d/mjs.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]